import Head from "next/head";

import { Poppins } from "next/font/google";
import Admin from "../templates/Admin";
import React from "react";
import { PrivateRoute } from "@/templates/PrivateRoute";

const poppins = Poppins({
  weight: "500",
  subsets: ["latin"],
});

export default function HomePage() {
  return (
    <>
      <Head>
        <title>LottoCrypto2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={poppins.className}>
        <PrivateRoute>
          <Admin />
        </PrivateRoute>
      </main>
    </>
  );
}
