import Head from "next/head";

import { Poppins } from "next/font/google";
import Home from "@/templates/Home";
import AppLayout from "@/layouts/AppLayout";

const poppins = Poppins({
  weight: "500",
  subsets: ["latin"],
});

export default function HomePage() {
  return (
    <>
      <Head>
        <title>LottoCrypto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={poppins.className}>
        <AppLayout>
          <Home />
        </AppLayout>
      </main>
    </>
  );
}
